apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: dev
  name: helloworld-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: e880613/helloworld:v1
        name: helloworld